export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const GET_PROTFOLIO_START = "GET_PROTFOLIO_START"
export const GET_PROTFOLIO_SUCCESS = "GET_PROTFOLIO_SUCCESS"
export const GET_PROTFOLIO_FAIL = "GET_PROTFOLIO_FAIL"
export const GET_PROTFOLIO = "GET_PROTFOLIO"

export const GET_TRANSACTIONS_START = "GET_TRANSACTIONS_START"
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS"
export const GET_TRANSACTIONS_FAIL = "GET_TRANSACTIONS_FAIL"

export const ADD_STOCK_START = "ADD_STOCK_START"
export const ADD_STOCK_SUCCESS = "ADD_STOCK_SUCCESS"
export const ADD_STOCK_FAIL = "ADD_STOCK_FAIL"

export const SET_USER = "SET_USER"
